engines:

  phpcodesniffer:
    enabled: true
    config:
      ignore_warnings: true
      file_extensions: "php,inc,phtml"

  duplication:
    enabled: false
    config:
      languages:
        - "php"

  phan:
    enabled: true
    config:
      file_extensions: [ "php", "inc", "phtml"]

  phpmd:
    enabled: true


exclude_patterns:
- "includes/*.php"
